# Generated by Django 3.0.3 on 2020-03-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('moviename', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('movieimg', models.ImageField(height_field=250, upload_to='accounts/static/', width_field=168)),
            ],
        ),
    ]
