# Generated by Django 3.0.3 on 2020-03-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieupdate', '0002_auto_20200315_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieimg',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
